name: Patch Tuesday Webscraper

on: 
    schedule:
    # For AEST (UTC+10), running at 10 PM UTC the previous day
    - cron: '0 22 7-13 * 2'
    # For AEDT (UTC+11), running at 9 PM UTC the previous day
    - cron: '0 21 7-13 * 2'
    workflow_dispatch:

jobs: 
    scraper:
        runs-on: ubuntu-latest
        steps:

            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Setup Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.9'
            
            - name: Install Packages
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
                pip install tabulate

            - name: Execute Script
              run: python main.py

            - name: Commit any changes
              uses: stefanzweifel/git-auto-commit-action@v4
              with:
                commit_message: Update CSV and Email notifications
              id: auto-commit-action

            - name: Get current month and year
              id: date
              run: |
                echo "CURRENT_MONTH=$(date +'%B')" >> $GITHUB_ENV
                echo "CURRENT_YEAR=$(date +'%Y')" >> $GITHUB_ENV

            - name: Send an Email
              if: steps.auto-commit-action.outputs.changes_detected == 'true'
              uses: dawidd6/action-send-mail@v3
              with:
                server_address: smtp.gmail.com
                server_port: 465
                username: ${{secrets.MAIL_USERNAME}}
                password: ${{secrets.MAIL_PASSWORD}}
                subject: 'New!! Microsoft Patch Tuesday'
                to: cpagutaisidro@aucloud.com.au
                cc: nballal@aucloud.com.au, mdolores@aucloud.com.au
                from: Patch Tuesday Scraper
                html_body: file://Email-Notification.md
                convert_markdown: true
                attachments: ./spreadsheets/${{ env.CURRENT_YEAR }}/${{ env.CURRENT_MONTH }}/Patch-Tuesday-${{ env.CURRENT_MONTH }}-${{ env.CURRENT_YEAR }}.xlsx
